
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1221, 910)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color:rgb(135,206,235,30);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.widget = QtWidgets.QWidget(self.page)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(744, 646))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_11.addWidget(self.tableWidget, 1, 0, 1, 1)
        self.widget_9 = QtWidgets.QWidget(self.tab_5)
        self.widget_9.setMinimumSize(QtCore.QSize(200, 0))
        self.widget_9.setStyleSheet("background-color: rgb(190, 190, 190);\n"
"\n"
"background-color: rgb(84, 168, 252);")
        self.widget_9.setObjectName("widget_9")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget_9)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 181, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.upload_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.upload_button.setFont(font)
        self.upload_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.upload_button.setObjectName("upload_button")
        self.verticalLayout.addWidget(self.upload_button)
        self.pushButton_19 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_19.setObjectName("pushButton_19")
        self.verticalLayout.addWidget(self.pushButton_19)
        self.gridLayoutWidget = QtWidgets.QWidget(self.widget_9)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 240, 181, 81))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 0, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 1, 0, 1, 1)
        self.no_row_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.no_row_label.setFont(font)
        self.no_row_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.no_row_label.setText("")
        self.no_row_label.setAlignment(QtCore.Qt.AlignCenter)
        self.no_row_label.setObjectName("no_row_label")
        self.gridLayout_3.addWidget(self.no_row_label, 0, 1, 1, 1)
        self.no_column_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.no_column_label.setFont(font)
        self.no_column_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.no_column_label.setText("")
        self.no_column_label.setAlignment(QtCore.Qt.AlignCenter)
        self.no_column_label.setObjectName("no_column_label")
        self.gridLayout_3.addWidget(self.no_column_label, 1, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.widget_9)
        self.label_26.setGeometry(QtCore.QRect(10, 190, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_11.addWidget(self.widget_9, 0, 1, 2, 1)
        self.textEdit = QtWidgets.QTextEdit(self.tab_5)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_11.addWidget(self.textEdit, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.widget_11 = QtWidgets.QWidget(self.tab_6)
        self.widget_11.setObjectName("widget_11")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.widget_11)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.widget_11)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.gridLayout_14.addWidget(self.tableWidget_2, 0, 0, 1, 1)
        self.outputBox = QtWidgets.QTextEdit(self.widget_11)
        self.outputBox.setMaximumSize(QtCore.QSize(16777215, 250))
        self.outputBox.setObjectName("outputBox")
        self.gridLayout_14.addWidget(self.outputBox, 1, 0, 1, 1)
        self.widget_13 = QtWidgets.QWidget(self.widget_11)
        self.widget_13.setMinimumSize(QtCore.QSize(250, 0))
        self.widget_13.setStyleSheet("background-color: rgb(190, 190, 190);\n"
"\n"
"background-color: rgb(84, 168, 252);")
        self.widget_13.setObjectName("widget_13")
        self.layoutWidget = QtWidgets.QWidget(self.widget_13)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 530, 124, 170))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.resample_button = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.resample_button.setFont(font)
        self.resample_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.resample_button.setObjectName("resample_button")
        self.gridLayout_17.addWidget(self.resample_button, 3, 0, 1, 1)
        self.data_split_button = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.data_split_button.setFont(font)
        self.data_split_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.data_split_button.setObjectName("data_split_button")
        self.gridLayout_17.addWidget(self.data_split_button, 2, 0, 1, 1)
        self.treat_outliers_button = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.treat_outliers_button.setFont(font)
        self.treat_outliers_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.treat_outliers_button.setObjectName("treat_outliers_button")
        self.gridLayout_17.addWidget(self.treat_outliers_button, 1, 0, 1, 1)
        self.data_scaling_button = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.data_scaling_button.setFont(font)
        self.data_scaling_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.data_scaling_button.setObjectName("data_scaling_button")
        self.gridLayout_17.addWidget(self.data_scaling_button, 0, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.widget_13)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 70, 231, 151))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_27.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_4.addWidget(self.label_27, 0, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_25.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_4.addWidget(self.label_25, 1, 0, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_46.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.gridLayout_4.addWidget(self.label_46, 2, 0, 1, 1)
        self.splitLineEdit_test = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.splitLineEdit_test.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.splitLineEdit_test.setObjectName("splitLineEdit_test")
        self.gridLayout_4.addWidget(self.splitLineEdit_test, 0, 1, 1, 1)
        self.splitLineEdit_training = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.splitLineEdit_training.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.splitLineEdit_training.setObjectName("splitLineEdit_training")
        self.gridLayout_4.addWidget(self.splitLineEdit_training, 1, 1, 1, 1)
        self.splitLineEdit_validation = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.splitLineEdit_validation.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.splitLineEdit_validation.setObjectName("splitLineEdit_validation")
        self.gridLayout_4.addWidget(self.splitLineEdit_validation, 2, 1, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.widget_13)
        self.label_47.setGeometry(QtCore.QRect(10, 30, 231, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.widget_13)
        self.label_48.setGeometry(QtCore.QRect(40, 370, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.widget_13)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(40, 420, 181, 81))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_49 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.gridLayout_5.addWidget(self.label_49, 0, 0, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName("label_50")
        self.gridLayout_5.addWidget(self.label_50, 1, 0, 1, 1)
        self.pre_process_row_no = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pre_process_row_no.setFont(font)
        self.pre_process_row_no.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pre_process_row_no.setText("")
        self.pre_process_row_no.setAlignment(QtCore.Qt.AlignCenter)
        self.pre_process_row_no.setObjectName("pre_process_row_no")
        self.gridLayout_5.addWidget(self.pre_process_row_no, 0, 1, 1, 1)
        self.pre_process_column_no = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pre_process_column_no.setFont(font)
        self.pre_process_column_no.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pre_process_column_no.setText("")
        self.pre_process_column_no.setAlignment(QtCore.Qt.AlignCenter)
        self.pre_process_column_no.setObjectName("pre_process_column_no")
        self.gridLayout_5.addWidget(self.pre_process_column_no, 1, 1, 1, 1)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.widget_13)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 250, 131, 91))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.oversampling_checkbox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.oversampling_checkbox.setFont(font)
        self.oversampling_checkbox.setObjectName("oversampling_checkbox")
        self.buttonGroup_7 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_7.setObjectName("buttonGroup_7")
        self.buttonGroup_7.addButton(self.oversampling_checkbox)
        self.verticalLayout_8.addWidget(self.oversampling_checkbox)
        self.undersampling_checkbox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.undersampling_checkbox.setFont(font)
        self.undersampling_checkbox.setObjectName("undersampling_checkbox")
        self.buttonGroup_7.addButton(self.undersampling_checkbox)
        self.verticalLayout_8.addWidget(self.undersampling_checkbox)
        self.gridLayout_14.addWidget(self.widget_13, 0, 1, 2, 1)
        self.gridLayout_13.addWidget(self.widget_11, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.gridLayout_34 = QtWidgets.QGridLayout(self.tab_11)
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.widget_17 = QtWidgets.QWidget(self.tab_11)
        self.widget_17.setObjectName("widget_17")
        self.gridLayout_35 = QtWidgets.QGridLayout(self.widget_17)
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.resultsTable = QtWidgets.QTableWidget(self.widget_17)
        self.resultsTable.setObjectName("resultsTable")
        self.resultsTable.setColumnCount(0)
        self.resultsTable.setRowCount(0)
        self.gridLayout_35.addWidget(self.resultsTable, 0, 0, 1, 1)
        self.resultsTextBox = QtWidgets.QTextEdit(self.widget_17)
        self.resultsTextBox.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.resultsTextBox.setFont(font)
        self.resultsTextBox.setObjectName("resultsTextBox")
        self.gridLayout_35.addWidget(self.resultsTextBox, 1, 0, 1, 1)
        self.widget_18 = QtWidgets.QWidget(self.widget_17)
        self.widget_18.setMinimumSize(QtCore.QSize(250, 0))
        self.widget_18.setStyleSheet("background-color: rgb(190, 190, 190);\n"
"\n"
"background-color: rgb(84, 168, 252);")
        self.widget_18.setObjectName("widget_18")
        self.label_4 = QtWidgets.QLabel(self.widget_18)
        self.label_4.setGeometry(QtCore.QRect(10, 0, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.widget_18)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 60, 296, 421))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.model_checkbox_1 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.model_checkbox_1.setFont(font)
        self.model_checkbox_1.setObjectName("model_checkbox_1")
        self.verticalLayout_4.addWidget(self.model_checkbox_1)
        self.model_checkbox_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.model_checkbox_2.setFont(font)
        self.model_checkbox_2.setObjectName("model_checkbox_2")
        self.verticalLayout_4.addWidget(self.model_checkbox_2)
        self.model_checkbox_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.model_checkbox_3.setFont(font)
        self.model_checkbox_3.setObjectName("model_checkbox_3")
        self.verticalLayout_4.addWidget(self.model_checkbox_3)
        self.model_checkbox_4 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.model_checkbox_4.setFont(font)
        self.model_checkbox_4.setObjectName("model_checkbox_4")
        self.verticalLayout_4.addWidget(self.model_checkbox_4)
        self.model_checkbox_5 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.model_checkbox_5.setFont(font)
        self.model_checkbox_5.setObjectName("model_checkbox_5")
        self.verticalLayout_4.addWidget(self.model_checkbox_5)
        self.model_checkbox_6 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.model_checkbox_6.setFont(font)
        self.model_checkbox_6.setObjectName("model_checkbox_6")
        self.verticalLayout_4.addWidget(self.model_checkbox_6)
        self.model_checkbox_7 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.model_checkbox_7.setFont(font)
        self.model_checkbox_7.setObjectName("model_checkbox_7")
        self.verticalLayout_4.addWidget(self.model_checkbox_7)
        self.model_checkbox_8 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.model_checkbox_8.setFont(font)
        self.model_checkbox_8.setObjectName("model_checkbox_8")
        self.verticalLayout_4.addWidget(self.model_checkbox_8)
        self.model_checkbox_9 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.model_checkbox_9.setFont(font)
        self.model_checkbox_9.setObjectName("model_checkbox_9")
        self.verticalLayout_4.addWidget(self.model_checkbox_9)
        self.model_checkbox_10 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.model_checkbox_10.setFont(font)
        self.model_checkbox_10.setObjectName("model_checkbox_10")
        self.verticalLayout_4.addWidget(self.model_checkbox_10)
        self.model_checkbox_11 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.model_checkbox_11.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.model_checkbox_11.setFont(font)
        self.model_checkbox_11.setAutoFillBackground(False)
        self.model_checkbox_11.setObjectName("model_checkbox_11")
        self.verticalLayout_4.addWidget(self.model_checkbox_11)
        self.build_models_button = QtWidgets.QPushButton(self.widget_18)
        self.build_models_button.setGeometry(QtCore.QRect(40, 600, 191, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.build_models_button.setFont(font)
        self.build_models_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.build_models_button.setObjectName("build_models_button")
        self.gridLayout_35.addWidget(self.widget_18, 0, 1, 2, 1)
        self.gridLayout_34.addWidget(self.widget_17, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_11, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.MplWidget = MplWidget(self.tab_3)
        self.MplWidget.setObjectName("MplWidget")
        self.gridLayout_7.addWidget(self.MplWidget, 0, 0, 1, 1)
        self.widget_19 = QtWidgets.QWidget(self.tab_3)
        self.widget_19.setMinimumSize(QtCore.QSize(250, 0))
        self.widget_19.setMaximumSize(QtCore.QSize(250, 16777215))
        self.widget_19.setStyleSheet("background-color: rgb(190, 190, 190);\n"
"\n"
"background-color: rgb(84, 168, 252);")
        self.widget_19.setObjectName("widget_19")
        self.label_5 = QtWidgets.QLabel(self.widget_19)
        self.label_5.setGeometry(QtCore.QRect(10, 0, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.widget_19)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 60, 296, 421))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.model_checkbox_12 = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.model_checkbox_12.setFont(font)
        self.model_checkbox_12.setObjectName("model_checkbox_12")
        self.verticalLayout_9.addWidget(self.model_checkbox_12)
        self.model_checkbox_13 = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.model_checkbox_13.setFont(font)
        self.model_checkbox_13.setObjectName("model_checkbox_13")
        self.verticalLayout_9.addWidget(self.model_checkbox_13)
        self.model_checkbox_14 = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.model_checkbox_14.setFont(font)
        self.model_checkbox_14.setObjectName("model_checkbox_14")
        self.verticalLayout_9.addWidget(self.model_checkbox_14)
        self.model_checkbox_15 = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.model_checkbox_15.setFont(font)
        self.model_checkbox_15.setObjectName("model_checkbox_15")
        self.verticalLayout_9.addWidget(self.model_checkbox_15)
        self.model_checkbox_16 = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.model_checkbox_16.setFont(font)
        self.model_checkbox_16.setObjectName("model_checkbox_16")
        self.verticalLayout_9.addWidget(self.model_checkbox_16)
        self.model_checkbox_17 = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.model_checkbox_17.setFont(font)
        self.model_checkbox_17.setObjectName("model_checkbox_17")
        self.verticalLayout_9.addWidget(self.model_checkbox_17)
        self.model_checkbox_18 = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.model_checkbox_18.setFont(font)
        self.model_checkbox_18.setObjectName("model_checkbox_18")
        self.verticalLayout_9.addWidget(self.model_checkbox_18)
        self.model_checkbox_19 = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.model_checkbox_19.setFont(font)
        self.model_checkbox_19.setObjectName("model_checkbox_19")
        self.verticalLayout_9.addWidget(self.model_checkbox_19)
        self.model_checkbox_20 = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.model_checkbox_20.setFont(font)
        self.model_checkbox_20.setObjectName("model_checkbox_20")
        self.verticalLayout_9.addWidget(self.model_checkbox_20)
        self.model_checkbox_21 = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.model_checkbox_21.setFont(font)
        self.model_checkbox_21.setObjectName("model_checkbox_21")
        self.verticalLayout_9.addWidget(self.model_checkbox_21)
        self.model_checkbox_22 = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        self.model_checkbox_22.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.model_checkbox_22.setFont(font)
        self.model_checkbox_22.setAutoFillBackground(False)
        self.model_checkbox_22.setObjectName("model_checkbox_22")
        self.verticalLayout_9.addWidget(self.model_checkbox_22)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.widget_19)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(30, 540, 201, 131))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.build_models_button_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.build_models_button_2.setFont(font)
        self.build_models_button_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.build_models_button_2.setObjectName("build_models_button_2")
        self.verticalLayout_2.addWidget(self.build_models_button_2)
        self.build_models_button_3 = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.build_models_button_3.setFont(font)
        self.build_models_button_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.build_models_button_3.setObjectName("build_models_button_3")
        self.verticalLayout_2.addWidget(self.build_models_button_3)
        self.gridLayout_7.addWidget(self.widget_19, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.widget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.widget_2 = QtWidgets.QWidget(self.page_2)
        self.widget_2.setStyleSheet("background-color: rgb(29, 218, 255);")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.widget_10 = QtWidgets.QWidget(self.widget_2)
        self.widget_10.setMinimumSize(QtCore.QSize(762, 664))
        self.widget_10.setMaximumSize(QtCore.QSize(762, 664))
        self.widget_10.setStyleSheet("background-color: rgb(29, 218, 255);")
        self.widget_10.setObjectName("widget_10")
        self.label_15 = QtWidgets.QLabel(self.widget_10)
        self.label_15.setGeometry(QtCore.QRect(230, 300, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.widget_10)
        self.label_16.setGeometry(QtCore.QRect(230, 400, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_14 = QtWidgets.QLabel(self.widget_10)
        self.label_14.setGeometry(QtCore.QRect(230, 190, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.lineEdit = QtWidgets.QLineEdit(self.widget_10)
        self.lineEdit.setGeometry(QtCore.QRect(230, 220, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(3, 3, 3);")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_21 = QtWidgets.QLabel(self.widget_10)
        self.label_21.setGeometry(QtCore.QRect(230, 440, 291, 21))
        self.label_21.setStyleSheet("color: rgb(3, 122, 43);")
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_10)
        self.lineEdit_2.setGeometry(QtCore.QRect(230, 340, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(3, 3, 3);")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_13 = QtWidgets.QLabel(self.widget_10)
        self.label_13.setGeometry(QtCore.QRect(270, 60, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(34)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_13.setObjectName("label_13")
        self.pushButton_15 = QtWidgets.QPushButton(self.widget_10)
        self.pushButton_15.setGeometry(QtCore.QRect(280, 440, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_15.setObjectName("pushButton_15")
        self.layoutWidget1 = QtWidgets.QWidget(self.widget_10)
        self.layoutWidget1.setGeometry(QtCore.QRect(230, 550, 1543, 472))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("panocean-logo.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Newcross-Exploration-and-Production-Limited.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Newcross-Petroleum-Limited.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.gridLayout_12.addWidget(self.widget_10, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.widget_2, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.page_7)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.widget_14 = QtWidgets.QWidget(self.page_7)
        self.widget_14.setStyleSheet("background-color: rgb(84, 169, 253);")
        self.widget_14.setObjectName("widget_14")
        self.splitter = QtWidgets.QSplitter(self.widget_14)
        self.splitter.setGeometry(QtCore.QRect(310, 190, 231, 151))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.comboBox_68 = QtWidgets.QComboBox(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_68.setFont(font)
        self.comboBox_68.setStyleSheet("background-color: rgb(0, 135, 202);\n"
"background-color: rgb(255, 255, 255);")
        self.comboBox_68.setObjectName("comboBox_68")
        self.comboBox_68.addItem("")
        self.comboBox_68.addItem("")
        self.comboBox_68.addItem("")
        self.pushButton_27 = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setStyleSheet("background-color: rgb(172, 172, 172);")
        self.pushButton_27.setObjectName("pushButton_27")
        self.gridLayout_24.addWidget(self.widget_14, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_7)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1221, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuConnect = QtWidgets.QMenu(self.menubar)
        self.menuConnect.setObjectName("menuConnect")
        self.menuSwitch = QtWidgets.QMenu(self.menubar)
        self.menuSwitch.setObjectName("menuSwitch")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_File = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.actionSave_File.setFont(font)
        self.actionSave_File.setObjectName("actionSave_File")
        self.actionCalculate_Back_Allocation = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.actionCalculate_Back_Allocation.setFont(font)
        self.actionCalculate_Back_Allocation.setObjectName("actionCalculate_Back_Allocation")
        self.actionMake_DB_Connection = QtWidgets.QAction(MainWindow)
        self.actionMake_DB_Connection.setObjectName("actionMake_DB_Connection")
        self.actionOML_24 = QtWidgets.QAction(MainWindow)
        self.actionOML_24.setObjectName("actionOML_24")
        self.actionOML_147 = QtWidgets.QAction(MainWindow)
        self.actionOML_147.setObjectName("actionOML_147")
        self.actionOML_152 = QtWidgets.QAction(MainWindow)
        self.actionOML_152.setObjectName("actionOML_152")
        self.actionUpload_File = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.actionUpload_File.setFont(font)
        self.actionUpload_File.setObjectName("actionUpload_File")
        self.menuFile.addAction(self.actionSave_File)
        self.menuFile.addAction(self.actionUpload_File)
        self.menuConnect.addAction(self.actionMake_DB_Connection)
        self.menuSwitch.addAction(self.actionOML_24)
        self.menuSwitch.addAction(self.actionOML_147)
        self.menuSwitch.addAction(self.actionOML_152)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuConnect.menuAction())
        self.menubar.addAction(self.menuSwitch.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.upload_button.setText(_translate("MainWindow", "UPLOAD FILE"))
        self.pushButton_19.setText(_translate("MainWindow", "DOWNLOAD FILE"))
        self.label_18.setText(_translate("MainWindow", "ROWS"))
        self.label_19.setText(_translate("MainWindow", "COLUMNS"))
        self.label_26.setText(_translate("MainWindow", "FILE SHAPE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Data Upload Module"))
        self.resample_button.setText(_translate("MainWindow", "Resample Data"))
        self.data_split_button.setText(_translate("MainWindow", "Data Splitting"))
        self.treat_outliers_button.setText(_translate("MainWindow", "Treat Outliers"))
        self.data_scaling_button.setText(_translate("MainWindow", "Data Scaling"))
        self.label_27.setText(_translate("MainWindow", "Test Data"))
        self.label_25.setText(_translate("MainWindow", "Training Data"))
        self.label_46.setText(_translate("MainWindow", "Validation Data"))
        self.label_47.setText(_translate("MainWindow", "Enter Data Splitting Percentage"))
        self.label_48.setText(_translate("MainWindow", "FILE SHAPE"))
        self.label_49.setText(_translate("MainWindow", "ROWS"))
        self.label_50.setText(_translate("MainWindow", "COLUMNS"))
        self.oversampling_checkbox.setText(_translate("MainWindow", "Oversampling"))
        self.undersampling_checkbox.setText(_translate("MainWindow", "Undersampling"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Data Pre-Processing Module"))
        self.label_4.setText(_translate("MainWindow", "MACHINE LEARNING MODELS"))
        self.model_checkbox_1.setText(_translate("MainWindow", "Logistic Regression"))
        self.model_checkbox_2.setText(_translate("MainWindow", "Decision Tree"))
        self.model_checkbox_3.setText(_translate("MainWindow", "Random Forest"))
        self.model_checkbox_4.setText(_translate("MainWindow", "Gradient Boosted Trees"))
        self.model_checkbox_5.setText(_translate("MainWindow", "Support Vector Machine"))
        self.model_checkbox_6.setText(_translate("MainWindow", "K Means"))
        self.model_checkbox_7.setText(_translate("MainWindow", "One-Class SVM"))
        self.model_checkbox_8.setText(_translate("MainWindow", "DB SCAN"))
        self.model_checkbox_9.setText(_translate("MainWindow", "Voting Classifier"))
        self.model_checkbox_10.setText(_translate("MainWindow", "Stacking Classifier"))
        self.model_checkbox_11.setText(_translate("MainWindow", "Semi-Supervised Label"))
        self.build_models_button.setText(_translate("MainWindow", "BUILD MODELS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), _translate("MainWindow", "Model Selection and Training Module"))
        self.label_5.setText(_translate("MainWindow", "MACHINE LEARNING MODELS"))
        self.model_checkbox_12.setText(_translate("MainWindow", "Logistic Regression"))
        self.model_checkbox_13.setText(_translate("MainWindow", "Decision Tree"))
        self.model_checkbox_14.setText(_translate("MainWindow", "Random Forest"))
        self.model_checkbox_15.setText(_translate("MainWindow", "Gradient Boosted Trees"))
        self.model_checkbox_16.setText(_translate("MainWindow", "Support Vector Machine"))
        self.model_checkbox_17.setText(_translate("MainWindow", "K Means"))
        self.model_checkbox_18.setText(_translate("MainWindow", "One-Class SVM"))
        self.model_checkbox_19.setText(_translate("MainWindow", "DB SCAN"))
        self.model_checkbox_20.setText(_translate("MainWindow", "Voting Classifier"))
        self.model_checkbox_21.setText(_translate("MainWindow", "Stacking Classifier"))
        self.model_checkbox_22.setText(_translate("MainWindow", "Semi-Supervised Label"))
        self.build_models_button_2.setText(_translate("MainWindow", "LOAD PLOT"))
        self.build_models_button_3.setText(_translate("MainWindow", "SAVE PLOT"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Results Visualisation and Interpretation Module"))
        self.label_15.setText(_translate("MainWindow", "Password"))
        self.label_14.setText(_translate("MainWindow", "Username"))
        self.label_13.setText(_translate("MainWindow", "LOGIN"))
        self.pushButton_15.setText(_translate("MainWindow", "Log In"))
        self.comboBox_68.setItemText(0, _translate("MainWindow", "OML 24"))
        self.comboBox_68.setItemText(1, _translate("MainWindow", "OML 147"))
        self.comboBox_68.setItemText(2, _translate("MainWindow", "OML 152"))
        self.pushButton_27.setText(_translate("MainWindow", "OK"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuConnect.setTitle(_translate("MainWindow", "Connect"))
        self.menuSwitch.setTitle(_translate("MainWindow", "Switch"))
        self.actionSave_File.setText(_translate("MainWindow", "Quit"))
        self.actionSave_File.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionCalculate_Back_Allocation.setText(_translate("MainWindow", "Calculate Back Allocation"))
        self.actionCalculate_Back_Allocation.setShortcut(_translate("MainWindow", "Ctrl+Alt+B"))
        self.actionMake_DB_Connection.setText(_translate("MainWindow", "Make DB Connection"))
        self.actionOML_24.setText(_translate("MainWindow", "OML 24"))
        self.actionOML_147.setText(_translate("MainWindow", "OML 147"))
        self.actionOML_152.setText(_translate("MainWindow", "OML 152"))
        self.actionUpload_File.setText(_translate("MainWindow", "Upload File"))

from mplwidget import MplWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

